"""empty message

Revision ID: 6ce60a60e006
Revises: 2fa56f0bf1c5
Create Date: 2019-12-31 12:17:51.793156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce60a60e006'
down_revision = '2fa56f0bf1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embeddings')
    op.add_column('sentence', sa.Column('embedding', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentence', 'embedding')
    op.create_table('embeddings',
    sa.Column('sentence_id', sa.DATETIME(), nullable=False),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['snippet.id'], ),
    sa.PrimaryKeyConstraint('sentence_id')
    )
    # ### end Alembic commands ###
