"""empty message

Revision ID: 704599acb880
Revises: 
Create Date: 2020-01-04 15:15:39.144269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704599acb880'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snippet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snippet_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('embedding', sa.PickleType(), nullable=False),
    sa.ForeignKeyConstraint(['snippet_id'], ['snippet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentence')
    op.drop_table('snippet')
    # ### end Alembic commands ###
